services:
  backend:
    image: danilly7/moneymgr:backend
    env_file:
      - backend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    image: danilly7/moneymgr:frontend
    ports:
      - "80:80"
    restart: unless-stopped
